In [13]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.tree import export_graphviz
import pydot
from joblib import dump

In [3]:
def permutation(lst): 
    if len(lst) == 0: 
        return [] 
    if len(lst) == 1: 
        return [lst] 
    l = [] 
    for i in range(len(lst)): 
       m = lst[i] 
       remLst = lst[:i] + lst[i+1:] 
       for p in permutation(remLst): 
           l.append([m] + p) 
    return l


In [4]:
def check(table):
    for i in range(3):
        if table[i][0]==table[i][1]==table[i][2]==1:
            return 1
        if table[i][0]==table[i][1]==table[i][2]==2:
            return 2
        if table[0][i]==table[1][i]==table[2][i]==1:
            return 1
        if table[0][i]==table[1][i]==table[2][i]==2:
            return 2
    if table[0][0]==table[1][1]==table[2][2]==1:
        return 1;
    if table[0][0]==table[1][1]==table[2][2]==2:
        return 2;
    if table[0][2]==table[1][1]==table[2][0]==1:
        return 1;
    if table[0][2]==table[1][1]==table[2][0]==2:
        return 2;
    return 0;

In [5]:
def calculateTableTarget(lst):
    table = np.zeros([3, 3])
    for i in range(len(lst)):
        x = (lst[i]-1) // 3
        y = (lst[i]-1) % 3
        table[x][y]=(i % 2) + 1
        target = check(table)
        if target==1 or target == 2:
            return target
    return 0

In [6]:
def calculateTarget(data):
    targets = []
    for lst in data:
        targets.append(calculateTableTarget(lst))
    return targets

In [7]:
data = np.arange(1, 10, 1).tolist() 
data = permutation(data)
targets = calculateTarget(data)

In [8]:
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'gini', random_state = 42)
classifier.fit(data, targets)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [9]:
p = classifier.predict(data)

In [10]:
print(confusion_matrix(targets, p))

[[ 46080      0      0]
 [     0 212223     33]
 [     0    123 104421]]


In [11]:
errors = 0
for i in range(len(targets)):
    if targets[i] != p[i]:
        errors += 1
accuracy = 100 - errors / len(targets) * 100
print(accuracy)

99.95701058201058


In [14]:
dump(classifier, "tic_tac_toe.model")

['tic_tac_toe.model']